version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MONGO_URI: mongodb://db:27017/seo_analysis
    restart: always
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.tasks:celery_app", "worker", "--loglevel=info", "--pool=solo"]
    depends_on:
      - redis
      - db
    environment:
      MONGO_URI: mongodb://db:27017/seo_analysis
      CELERY_BROKER_URL: redis://redis:6379/0 # Explicit broker URL
      CELERY_RESULT_BACKEND: redis://redis:6379/0 #  backend URL
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongodb_data_container: