version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=mongodb://user:password@db:27017/seo_analysis

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=mongodb://user:password@db:27017/seo_analysis

  redis:
    image: redis:alpine

  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: seo_analysis
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: